on:
  push:
    paths:
      - 'strimzi-kafka-connect/**'
    branches:
      - feat/sre-4435-custom-strimzi-image
  pull_request:

env:
  IMAGE_NAME: strimzi-kafka-connect
  STRIMZI_VERSION: 0.27.1-kafka-2.8.1

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    timeout-minutes: 90
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.0

      - name: Build Docker Image
        run: cd strimzi-kafka-connect && docker build -t ${{ github.sha }} . --build-arg github_sha=${{ github.sha }}

      - name: Log in to registry
        # if: github.ref == 'refs/heads/main'
        # This is where you will update the PAT to GITHUB_TOKEN
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        if: ${{ github.event.repository.default_branch == github.ref_name }}
        run: |
          # Set variables
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          SHA_SHORT=$(git rev-parse --short HEAD)
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          
          # Strip git ref prefix from version
          docker tag ${{ github.sha }} ${STRIMZI_VERSION}-${SHA_SHORT}
          docker push $IMAGE_ID:${STRIMZI_VERSION}-${SHA_SHORT}
